language: python
python: 3.8

cache: pip

branches:
    only: master

install:
    - pip install -r ./docs/requirements.txt

script:
    - ./test/test_filename_convention.py
    - mkdocs build --strict

env:
    global:
        secure: "vy/CahBFUP3Yx9enVv55AnOjmca81uEMUv5NMthJwk8jG+l6DtGc3HUXETk6bdFeQfyIvRvR3K3VIQb+vIJYYdK+uYu9TxAw1umlOtA+MeBXOt5TCycFvW+NyaS2VVK6LnuZ4HCnQGGJJZhyfxTQH/MtDrz7x3HBC5QAIdU67rUnCDxxO3Qi3vTzfBgAVHrqu8Cym9F1lUo0PB26ZvM6fJAvLYn9/jyefFOLxwG9UsP6WB/4S1jyAMMzEbNXrkt0/Bh1g8e/UT8Lw8gYw4Zu27Ox1FqZ01py4pkoOhiNNqZE8/59y5NtfHtm3lWKAuzkk+1x+M6nk6DTKC+6J7tCHHy8RF3+wag2AbOzinPAG744Rs0ysMq1J/gCEo6GUaicWlXSm8ZhatdkcIGxQLbWvmEHBoPIgGf+hBRdWIfSfx2IO8OfqtyvFfubvtJ/dchBCU6NUm2jZ5EV03kpMWSAKXmue6aQzbPsVHjOh2RuKNuMmXPtCWpEuyyXggIK7XvtRKODh9SXYEm/xKhFjBzexFrpNh54LbxbjHdl6ip+WLtctABPGgwfgPvH1bcltXnjZwBdB+6jLa11xEcS927EasAhvQRq0+r8bDKuq/ICiM6O+CpXmTDGEVBGO3gv8JtE6OWdt3H5meK1+EXRMuxKpBKwnvO7yiFsLxiWsp+JR/A="

deploy:
    provider: pages
    edge: true
    github_token: $GH_TOKEN
    on:
        branch: master
    target_branch: gh-pages
    local_dir: site
