language: python
python: 3.8

cache: pip

branches:
    only: master

install:
    - pip install -r ./docs/requirements.txt

script:
    - git clean -f -d -x
    - git config --global user.name "Travis CI"
    - git config --global user.email "travis@travis-ci.com"
    - git remote add gh-token "https://${GH_TOKEN}@github.com/umd-lhcb/lhcb-ntuples-gen.git"
    - git fetch gh-token && git fetch gh-token gh-pages:gh-pages

after_success:
    - mkdocs gh-deploy -v --clean --remote-name gh-token
env:
    global:
        - secure: F80Yh0AxD/QKg6v06ONphXgHwjk4D+q/heADn2rbOyyufX7tHfncj4fAVAHK4sKsoGNNrZogeGcpo/uRXE8Tq0etOPOU7T7Py3ujKamSAo8fApRlgZIrFRO8nzgOCrtEp5npIoeazG9gbGWqZPoJkqY3ZWL5qWWejFkYohh5SYJdzADiK7DoqPbpjq8R2s0vRgRxeobxk/4TTPEF5GrQI/2+43RldmGiFjCsxmv9cOSyfouoiKu0x3p5eoLlxdvFF4tQYehBgxvbxG+d7WUwt/spaCPWgqUOGogYP1HfCgzst9vNOAZ8ruF16MuXBZIK4PsRZNPH9dRSfbRtYtU/xMecr34859C463+WapeNdwgTV/eQJp+EiWg2RlOiQnxA+EMqIsU0AHUsSDLVsHOhfZsrtgR4cpz2Z29Y+KbpIjqRcZcsbfQUs33cAtBjAQVUshPdyv/EMBy2vuaHqbJf3tzHal5SOn5rsmMBx4qdWoXV/PjVM8f7RT8GjDnXvFtFAuRnDFWS8H+1GoXylpqbRLplmLozFCJAvsNy6pc50l60UC0Ls+j4MBu1f9xwtZqXGYNLxCf5dXkTKulAkDq+MyCtJnrTzYxajKMkAyK3eWmvhI2Pu+T1jJ+7eiwXajrPOwsFcfczp42Z6/PhslM8fRVj//HEtRxcoIQrNZ0DGD0=
