site_name: 'lhcb-ntuples-gen wiki'
site_url: https://umd-lhcb.github.io/lhcb-ntuples-gen

repo_name: umd-lhcb/lhcb-ntuples-gen
repo_url: https://github.com/umd-lhcb/lhcb-ntuples-gen

theme:
    name: 'material'
    include_search_page: false
    feature:
        - instant

plugins:
    - search
    - markdownextradata

nav:
    - Home: index.md
    - Ntupling:
        - Installing dependencies: ntupling/installation.md
        - Step 1 ntuples with Davinci: ntupling/step1_davinci.md
        - Step 2 ntuples with babymaker: ntupling/step2_babymaker.md
        - Submitting DaVinci jobs to GRID: ntupling/grid_job.md
        - Developing this project: ntupling/dev.md
        - Nomenclature: ntupling/nomenclature.md
    - Software:
        - git-annex: software_manuals/git_annex.md
        - DaVinci:
            - Docker image usage: software_manuals/davinci/docker_image_usage.md
            - Tips and tricks: software_manuals/davinci/tips_and_tricks.md
            - LoKi functors: software_manuals/davinci/loki_functors.md
            - TupleTools: software_manuals/davinci/tuple_tools.md
        - nix: software_manuals/nix/nix.md
        - Compiling ROOT: software_manuals/root.md
        - bender: software_manuals/bender.md
        - DIRAC: software_manuals/dirac.md
        - Tips for lxplus: software_manuals/lxplus.md
        - External manuals: software_manuals/external.md
    - Physics:
        - Momentum scaling: physics/momentum_scaling.md
        - Wrong-sign particles: physics/wrong_sign_particles.md
        - B0 oscillation: physics/b0_oscillation.md
        - Track χ²/DOF inconsistency in run 2 data-MC: physics/track_chi2ndof_data_mc_inconsistency.md
        - Transverse energy: physics/transverse_energy.md
    - Technical concepts:
        - Truth matching: technical_concepts/truth_matching.md
    - Data:
        - Data management: data/data_management.md
        - Data sources: data/data_sources.md
        - Cutflows:
            - RDX validation cutflow: data/cutflows/RDX_run1_phoebe_vs_us.md
            - R(D*) cutflow overview: data/cutflows/RDst_run1_vs_run2/overview.md
            - R(D*) cutflow detail: data/cutflows/RDst_run1_vs_run2/detail.md
            - R(D*) cutflow to study the effect of refit D* only: data/cutflows/RDst_refit_Dst_only_vs_full_refit.md
        - Comparisons:
            - R(D*) variables, run 1: data/comparison/RDst_vars_run1/RDst_vars_run1.md
            - R(D*) run 1 step-2 cuts validation: data/comparison/RDst_step2_cuts_validation/RDst_step2_cuts_validation.md
            - Trigger lines: data/comparison/trigger_lines.md

markdown_extensions:
    - admonition
    - pymdownx.critic
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.superfences
    - pymdownx.caret
    - footnotes
    - codehilite

extra_javascript:
    - javascripts/config.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
    davinci_ver: v45r6
    davinci_sl_ver: v45r6-SL
    davinci_runtime: x86_64-centos7-gcc9-opt
    admin: Manuel or Yipeng
