#!/usr/bin/env bash
# Author: Yipeng Sun
# Last Change: Thu Aug 19, 2021 at 08:38 PM +0200

INPUT_NTP=$1
INPUT_YML=$2
OUTPUT_SUFFIX=$3

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
CPP_TMPL=$DIR/../../postprocess/cpp_templates/rdx.cpp
MU_BDT_WEIGHT=$DIR/../../run2-rdx/weights_run2_no_cut_ubdt.xml

HEADER_DIR=$DIR/../../include
COMPILER=$(root-config --cxx)
CXX_FLAGS=$(root-config --cflags)
LINK_FLAGS=$(root-config --libs)
ADDF_FLAGS="-I${HEADER_DIR}"

cpp_gen() {
    babymaker -i ${INPUT_YML} -o baby.cpp -n ${INPUT_NTP} -t ${CPP_TMPL} -f $@
}

cpp_compile() {
    ${COMPILER} ${CXX_FLAGS} ${ADDF_FLAGS} -o baby baby.cpp ${LINK_FLAGS}
}

aux_name() {
    DIRNAME=$(dirname ${INPUT_NTP})
    FILENAME=$(basename ${INPUT_NTP} .root)
    echo "${DIRNAME}/${FILENAME}__aux_mu_bdt.root"
}

add_mu_bdt() {
    AUX_FILE=$(aux_name)

    if [ -f ${AUX_FILE} ]; then
        echo "Auxiliary mu BDT ntuple already exist, use it directly..."
        ln -s ${AUX_FILE} mu_bdt.root
    else
        addUBDTBranch ${INPUT_NTP} "mu_isMuonTight" ${MU_BDT_WEIGHT} mu_bdt.root $@
        rm -rf ./weights  # This folder is generated by UBDT adder for unknown reason
    fi
}

add_mu_bdt "TupleB0/DecayTree" "TupleBminus/DecayTree"
cpp_gen mu_bdt.root
cpp_compile
./baby "--${OUTPUT_SUFFIX}"
